# Generated by Django 5.2 on 2025-05-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentattendance_studentqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqr',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
