# Generated by Django 5.2 on 2025-05-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_studentqr_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqr',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentQr', to='api.student'),
        ),
    ]
