# Generated by Django 5.2 on 2025-05-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_studentqr_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('CU', 'Complete Uniform'), ('IU', 'Incomplete Uniform')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_logs', to='api.student')),
            ],
        ),
    ]
